### PR TITLE
Pipelining

### LINKED ISSUE #1: Pipeline support
Thanks, this looks awesome.

Pipeline support would be greatly appreciated as this is lacking from the other redis binding I've used (https://github.com/0xffea/ocaml-redis)

I thought it would be good to mention it as it might require a bit of refactoring to make it work for all commands.

### PR DESCRIPTION
**Pull request by andersfugmann**
This PR adds pipelining support, so users can issue requests concurrently over a single connection. 

Since reply decoding is only done by one thread, `parse.ml` has been greatly simplified, and deleted `atomic_read` test. 

I also removed the ``` `Eof ``` error, as I believe its the same as ``` `Connection_closed```, which is returned if either ends closes the connection. 

This closes #1

### CODE REVIEW

**Comment by andersfugmann** [comment]
Travis complains that the PR does not build on async v0.11. I will fix that and maintain forward compatibility to async v0.12.

**Comment by andersfugmann** [comment]
Btw. I have a test program lying around to test that we handle Redis crashes correctly. For obvious reasons it cannot be part of the test suite, but It did help me identify a problem. Should I add it to the PR?

**Comment by Leonidas-from-XIV** [comment]
Yes, that'd be good. While I am not totally opposed to only using `v0.12` in the future this would mean that the only supported OCaml version for now would be 4.07.

(Also I have some beef with `v0.12` at the moment because it is missing UDP support so I can't upgrade to it)

**Comment by Leonidas-from-XIV** [comment]
> Should I add it to the PR?

Yes, please do. If it is not run as part of the regular tests it might bit-rot over time but it is still better than not having it.

**Comment by andersfugmann** [comment]
I've added the extra test and compatibility to core v0.11 has been restored. Merge at will :-)

**Comment by Leonidas-from-XIV** [comment]
Great, thanks! I'll try to review it today evening and cut a release ASAP.

**Pull request merged**
